<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Mapster" Version="10.0.6" />
    <PackageReference Include="Mapster.DependencyInjection" Version="10.0.6" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="QuestPDF" Version="2026.5.0" />
    <PackageReference Include="SkiaSharp" Version="3.119.4" />
    <PackageReference Include="ZXing.Net" Version="0.16.11" />
    <PackageReference Include="ZXing.Net.Bindings.SkiaSharp" Version="0.16.22" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SmartBus.Domain\SmartBus.Domain.csproj" />
  </ItemGroup>

</Project>
